 
# Ref: https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
blank_issues_enabled: true  # default: true
contact_links:

- name: "Ask Questions on Discord"
  url: https://safing.io/discord
  about: Get help from our great community

- name: "Wiki and FAQ"
  url: https://wiki.safing.io/
  about: Learn more about Portmaster in our Wiki

- name: "Contribution Guideline"
  url: https://docs.safing.io/portmaster/guides/contribute
  about: Learn how to best contribute and make sure your work is aligned with Safing’s current goals and focus

- name: "Code of Conduct"
  url: https://docs.safing.io/community/code-of-conduct
  about: Be nice to other community members
